### ISSUE TITLE
cursor not stopping at spaces correctly

### ISSUE THREAD

**Issue by megamrtota** [unilock/wordchars#1]
for example if we have text: "/tp ~ ~ ~|" (the symbol | is the cursor in this case) and then we press ctrl+left arrow the cursor goes to here "/|tp ~ ~ ~" which i think is incorrect? it is supposed to go here "/tp ~ ~| ~". the code handles spaces weirdly.

**Comment by unilock** [comment]
I just tested in a `zsh` prompt, and how the mod works now is indeed the intended behavior.

I'm not sure how I would handle spaces in the way you're describing without a rather large overhaul of the current logic.
